server:
  port : 8888
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
<<<<<<< HEAD
            allow-credentials: true
=======
            allow-credentials: true

>>>>>>> f46e121822e45e719aff23c6c67750c456a0d0c9
